### ISSUE TITLE
The example didn’t deploy in Okteto Cloud

### ISSUE THREAD

**Issue by jabrena** [okteto/java-maven-getting-started#6]
The example didn’t deploy in Okteto Cloud with the button.

**Comment by pchico83** [comment]
> The example didn’t deploy in Okteto Cloud with the button.
Hi @jabrena , which error did you get? We aren't able to repro it

**Comment by jabrena** [comment]
I have just clicked in the button:

![C34587B7-CC12-436F-AC90-828E4469B7B9](https://user-images.githubusercontent.com/147263/200466535-46c3737c-ecc4-4cb1-a588-b6021cb93856.jpeg)

and I received the following error in the deployment:

![2884095E-15B9-4483-91A5-23AD9042E61B](https://user-images.githubusercontent.com/147263/200464385-4594900e-cb54-4ce6-b9f5-7ae47ec7aac5.jpeg)

**Comment by jabrena** [comment]
Hi, did you have the opportunity to repeat the case?

**Comment by pchico83** [comment]
@jabrena there was an unhealthy node in the cluster, could you retry now?

**Comment by jabrena** [comment]
It is working now again.

During the week, I will send a PR with latest updates from Spring Boot.

I am going to close the issue.
